changelog: sed command compat

diff --git a/bin/generate-changelog b/bin/generate-changelog
--- a/bin/generate-changelog
+++ b/bin/generate-changelog
@@ -41,6 +41,16 @@ while [ $# -gt 0 ]; do
   shift $(( $# > 0 ? 1 : 0 ))
 done
 
+sed_command=sed
+if test $(uname) = 'Darwin'; then
+  sed_command=gsed
+  if ! type $sed_command &>/dev/null; then
+    printf "!! gnu-sed not found. \
+      Try install gnu-sed with 'brew install gnu-sed'\n"
+    exit 1
+  fi
+fi
+
 revision=""
 if ! test -z "$since"; then
   revision="$since..$until"
@@ -49,4 +59,6 @@ fi
 release_date=`date "+%Y-%m-%d"`
 
 printf "## $release_date, Version $version\n### Notable Changes\n* **Coming soon**\n\n### Commits\n"
-git log --format="[%h] - %s (%aN)" $revision | gsed -E "s/(\[.+\]) - (.+)\:/\* \1 - \*\*\2\*\*\:/g"
+git log --format="[%h] - %s (%aN)" $revision | \
+  command $sed_command -E "s/(\[.+\]) - /\* \1 - /g" | \
+  command $sed_command -E "s/ - (.+)\:/ - \*\*\1\*\*\:/g"
